### ISSUE TITLE
`-h` or `--help` CLI argument not found

### ISSUE THREAD

**Issue by thebrandonlucas** [cqb13/latin_words#1]
Hello, thank you for building this!

After building from the command line and running the binary and trying to read the documentation via `-h` or `--help`, I get the following:
```bash
./vocab-vault --h
Command not found: --h
```

```bash
./vocab-vault --help
Command not found: --help
```

**Comment by cqb13** [comment]
sorry about that. 

I rewrote the CLI and forgot to update the README with the new docs.

you can run ```./vocab-vault help``` for help info, or consult the README.

example commands can also be found in the README file
